apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batch
resources:
  - canary.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml

configMapGenerator:
  - name: batch-html
    files:
      - index.html=html/index.html
