apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-cluster
  namespace: batch
spec:
  interval: 24h
  url: oci://ghcr.io/crulabs/charts/cnpg-cluster
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "2.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: batch-postgres
  namespace: batch
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: cnpg-cluster
    namespace: batch
  values:
    type: postgresql
    version: 17
    initdb:
      database: batch
      secret:
        name: batch-postgres

    storage:
      size: 2Gi

    backup:
      enabled: true
      obc:
        name: batch-postgres-backups
