apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: batch-postgres-backups
  namespace: batch
spec:
  bucketName: batch-postgres-backups
  storageClassName: rook-ceph-bucket
