apiVersion: v1
kind: Secret
metadata:
    name: batch-postgres
    namespace: batch
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Co4Z,iv:PZpTDn2vlhK3dTBmZPj3fzYgVjK4BUPAazd3A+IA/FI=,tag:qwerO4Gls7x4jeita85cMA==,type:str]
    password: ENC[AES256_GCM,data:c8JWaAzYf+MpRyQQrpd9G/UtcbY5+wDEQTWKKEG8,iv:0f+7FnRV/TuAru+Ss0JroQQFzhBts6dcLHc3Ye1T9PU=,tag:veTm/AUyA6tqQ6wxPZBl8g==,type:str]
sops:
    lastmodified: "2026-05-31T16:32:16Z"
    mac: ENC[AES256_GCM,data:8O/6xIVpSjgpQJGlfZvRJvXdl/D8kdSANKz7qfQIDRwUddCefe5NNSPlBZvQKR94DOe6c7CU0kIdSpOO+R7mrKOu4/1D6f9FfJCsbT33T39DEOwXER0nhGFi6Dli7H6YLLdCvzArsUZnpr2pxmnS/Jd8RbPhHuJJhu/2zLVxLhE=,iv:2FtcaxglxbJrcG/jY/rmC69QukLnNZSF2kR0B2hKFuw=,tag:kocCQVAL+ONZVxxPw2A4iA==,type:str]
    pgp:
        - created_at: "2026-05-31T16:32:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//cSO+8g4HnmDzDI+zmACD2n6pfPU0x3Rzhv5j5bsIjYUS
            ScRePBJglUTLoJxbieNGY7IekkpDbw7yMb5BaiSfx4Y4paFBUZn26RD6eu1J1IPM
            yiAZ72alHOkaMTFdhuDHNSSmlEh25ie1PfvvidZ0KQbomu0bSayhLnL3J4vLakev
            wUNHQpyAScGtadBX36HxzrRxlbcdN2BfrAxYK83acKEWP7gJlzOhCuTuYFagzcab
            xUVf0+o3FPeWBrw2GGP/PlbIc7i1execjyfbzwpaHc+GkWWzNPDkqqQpDQh6eT00
            1IIHlKaf/gxnWsnC2Ch23HrDRRVa00LNkAIkj2A+lYMG4+/FWG7YREtkvATPuf3j
            Z547z1U8mmAuqWDzbVCiW53/dWm+zYIGObqLquv/GEkcq2lPFsyUhf1+B7gokJ9p
            2FOIwqY7LuJIfcft4lQph9msSomP91LgG23RmeiGK+pvSSbw7udSHtviCaNX16I5
            377RGf2XMuY3LVs0MckrQ21hXUYPIbO6iYO13Lwp+JVZ6mMBI1e7k/bVN/ew9Sn6
            +Yq1dCGJBuHiSrDoNckwH64TWGS+Eqv8Q70z4Z27aMmr7N0RoDD5iMLTnt3CRuJy
            +6mOpkVIQ1MGVXh83t8wM8k+kP1dSnKN6hQo1aE+cWxU36nTBa8M8wYdbddrZU3U
            aAEJAhDuwTphlRL719a9skreU+lCXEhaKiM3KDcYU96HapI9KqzkzJapovY3MHnb
            hy0zDvWuw8oVHgCOWyxPXpXJNY5+lSJzk6lLRoOCAfER+EaeCKksdIPF6k7f8Sdl
            tdTT+f00OrAL
            =ZX8S
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
